environment:
  width: 100
  height: 100
  boundary_condition: "torus"
  channels: 
    - "food"
    - "poison"
    - "obstacle"
    - "chemoattractant"
    - "chemorepellant"

  food_generation: "levy_dust"
  food_generation_params:
    pad: [0, 5]
    alpha: [0.1, 2]
    beta: [-1, 1] 
    num_food: [50, 500]

  poison_generation: "levy_dust"
  poison_generation_params:
    pad: [0, 5]
    alpha: [0.1, 2]
    beta: [-1, 1]
    num_poison: [20, 200]

  obstacle_generation: "perlin_noise"
  obstacle_generation_params:
    obstacle_generation_params:
    threshold: [0.05, 0.2]
    frequency: [4.0, 16.0]
    octaves: [1, 4]
    persistence: [0.25, 1.0]
    lacunarity: [1.5, 3.0]

  chemoattractant_params:
    iterations: 300
    dropoff: 1
    
  chemorepellant_params:
    iterations: 300
    dropoff: 1

visualize:
  colormaps:
    food: "Greens"
    poison: "Oranges"
    obstacle: "binary"
    chemoattractant: "Greens"
    chemorepellant: "Oranges"
  chemo_alpha: 0.9

interactive_sim:
  enable: true
  fps: 10
  save: false
  save_path: "ALife2023/interactive_sim"
  save_name: "interactive_sim"
  save_format: "gif"
  save_fps: 10
  save_start: 0
  save_end: 100
  save_every: 1
  save_colormaps:
    food: "Greens"
    poison: "Oranges"
    obstacle: "binary"
    chemoattractant: "Greens"
    chemorepellant: "Oranges"
  save_chemo_alpha: 0.5
  
lifecycle:
  spore_params:
    initial_muscle: 1.0
    initial_storage: 1.0
    initial_communication: "random"
  inoculation:
    num_spores: 3
    where_to_place: "on_food"
    selection_procedure: "random"
  stoppage:
    condition: "iterations"
    stoppage_range: [500, 1500] 
    stoppage_final: 0 # placeholder randomly updated

physiology:  
  channels:
    - "muscle"
    - "cytoplasm"
    - "storage"
    - "communication"

  perception_channels:
    - "obstacle"
    - "chemoattractant"
    - "chemorepellant"
    - "muscle"
    - "cytoplasm"
    - "storage"
    - "communication"

  actuators:
    - "rotate"      # %change in direction of flow, energy cost proportional to muscle size
    - "contraction" # %change in reservoir size (muscle) -- multiplied by open % TODO: Refractory period?
    - "delta_muscle"
    - "delta_storage"
  num_communication_channels: 10
  num_actuators: 17
  

  perception_kernel:
    kernel_type: "moore"
    kernel_radius: 1

physics:
  cytoplasm_absorption_rate: 0.1
  exchange_rates:
    food_to_cytoplasm: 5.0        # 1 food -> 5 cytoplasm 
    cytoplasm_to_storage: 0.5    # 1 cytoplasm -> 0.2 storage
    storage_to_muscle: 0.7       # 1 storage -> 0.7 muscle
    muscle_contraction_cost: 0.2  
  min_storage: 0.1
  muscle_max_size: 2.0
  storage_max_units: 10
  muscle_to_storage_atrophy_rate: 0.1