environment:
  width: 100
  height: 100
  boundary_condition: "torus"
  channels: 
    - "food"
    - "poison"
    - "obstacle"
    - "chemoattractant"
    - "chemorepellant"
  obstacle_generation: "perlin_noise"
  poison_generation: "levy_dust"
  food_generation: "levy_dust"
  food_generation_params:
    pad: 0
    alpha: 1
    beta: 1
    num_food: 300
  poison_generation_params:
    pad: 0
    alpha: 0.7
    beta: 0.5
    num_poison: 100
  obstacle_generation_params:
    threshold: 0.1
    frequency: 8.0
  chemoattractant_params:
    iterations: 20
    dropoff: 0.5
  chemorepellant_params:
    iterations: 20
    dropoff: 0.5



visualize:
  colormaps:
    food: "Greens"
    poison: "Oranges"
    obstacle: "binary"
    chemoattractant: "Greens"
    chemorepellant: "Oranges"
  chemo_alpha: 0.75
  

lifecycle:
  reproduction_metric: "iterations"
  reproduction_params:
    iterations: 1000


physiology:
  perceived_channels:
    - "obstacle"
    - "chemoattractant"
    - "chemorepellant"
    - "communication"
    - "nutrient_storage"
